comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

language: R

sudo: false

cache: packages

after_success:

- Rscript -e 'covr::codecov()'
